import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { jsonError, jsonOk } from "@/lib/http";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const envPath = path.join(process.cwd(), ".env.local");
const managedKeys = [
  "SPARKPLAY_PUBLIC_APP_URL",
  "SPARKPLAY_AUTH_SECRET",
  "SPARKPLAY_GITHUB_CLIENT_ID",
  "SPARKPLAY_GITHUB_CLIENT_SECRET"
] as const;

const configSchema = z.object({
  appUrl: z.string().url("请输入合法的应用地址，例如 http://localhost:3000"),
  authSecret: z.string().min(24, "登录签名密钥至少 24 位"),
  githubClientId: z.string().min(8, "请输入 GitHub OAuth Client ID"),
  githubClientSecret: z.string().min(20, "请输入 GitHub OAuth Client Secret")
});

export async function GET() {
  try {
    return jsonOk({
      writable: isLocalConfigWriteAllowed(),
      configured: isGitHubOAuthConfigured(),
      appUrl: process.env.SPARKPLAY_PUBLIC_APP_URL ?? "http://localhost:3000",
      needs: {
        appUrl: !process.env.SPARKPLAY_PUBLIC_APP_URL,
        authSecret: !process.env.SPARKPLAY_AUTH_SECRET,
        githubClientId: !process.env.SPARKPLAY_GITHUB_CLIENT_ID,
        githubClientSecret: !process.env.SPARKPLAY_GITHUB_CLIENT_SECRET
      }
    });
  } catch (error) {
    return jsonError(error);
  }
}

export async function POST(request: Request) {
  try {
    if (!isLocalConfigWriteAllowed()) {
      return jsonError(new Error("当前环境不允许从页面写入本地配置文件"), 403);
    }

    const payload = configSchema.parse(await request.json());
    const updates = {
      SPARKPLAY_PUBLIC_APP_URL: payload.appUrl.replace(/\/+$/, ""),
      SPARKPLAY_AUTH_SECRET: payload.authSecret,
      SPARKPLAY_GITHUB_CLIENT_ID: payload.githubClientId,
      SPARKPLAY_GITHUB_CLIENT_SECRET: payload.githubClientSecret
    };
    const current = await readEnvLocal();
    const next = upsertEnvValues(current, updates);
    await writeFile(envPath, next, "utf8");

    for (const [key, value] of Object.entries(updates)) {
      process.env[key] = value;
    }

    return jsonOk({
      ok: true,
      configured: true,
      path: ".env.local"
    });
  } catch (error) {
    return jsonError(error);
  }
}

function isGitHubOAuthConfigured(): boolean {
  return Boolean(
    process.env.SPARKPLAY_PUBLIC_APP_URL &&
      process.env.SPARKPLAY_AUTH_SECRET &&
      process.env.SPARKPLAY_GITHUB_CLIENT_ID &&
      process.env.SPARKPLAY_GITHUB_CLIENT_SECRET
  );
}

function isLocalConfigWriteAllowed(): boolean {
  return process.env.NODE_ENV !== "production" || process.env.SPARKPLAY_ALLOW_LOCAL_CONFIG_WRITE === "true";
}

async function readEnvLocal(): Promise<string> {
  try {
    return await readFile(envPath, "utf8");
  } catch (error) {
    if (isNotFoundError(error)) return "";
    throw error;
  }
}

function upsertEnvValues(content: string, updates: Record<(typeof managedKeys)[number], string>): string {
  const seen = new Set<string>();
  const lines = content.split(/\r?\n/).map((line) => {
    const match = line.match(/^([A-Z0-9_]+)=/);
    if (!match) return line;
    const key = match[1] as (typeof managedKeys)[number];
    if (!managedKeys.includes(key)) return line;
    seen.add(key);
    return `${key}=${formatEnvValue(updates[key])}`;
  });

  const additions = managedKeys
    .filter((key) => !seen.has(key))
    .map((key) => `${key}=${formatEnvValue(updates[key])}`);
  const trimmed = lines.join("\n").replace(/\s+$/g, "");
  if (additions.length === 0) return `${trimmed}\n`;
  const prefix = trimmed.length > 0 ? `${trimmed}\n\n` : "";
  return `${prefix}# GitHub OAuth login, generated by SparkPlay local config helper.\n${additions.join("\n")}\n`;
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function isNotFoundError(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}
